#!/usr/bin/env sh

# Number of threads used by pytorch in each task.
n_threads=1

# Input parameter file.
param_file="inputs/input_laptop_sobol_ndim2_nc_mass_1e14_1e15_10_z_0.toml"

# Output directory.
output_dir="/home/isaezcasares/data/mls/trained_models_laptop/sobol_ndim2/nc_mass_1e14_1e15_10_z_0"

# Make output directory.
mkdir -p $output_dir

uv run python main.py train -n $n_threads -f $param_file -o $output_dir &> ${output_dir}/train_example.log &
